backend:
  name: github
  repo: junthong/junthong.github.io
  branch: prepublish
  site_domain: statuesque-granita-8c2c00.netlify.com
publish_mode: editorial_workflow
media_folder: "m/uploads"
collections:
  - name: "articles" # Used in routes, e.g., /admin/collections/blog
    label: "articles" # Used in the UI
    folder: "_articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      #- {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Tags", name: "tags", widget: list}
      - {label: "Body", name: "body", widget: "markdown"}