backend:
  name: github
  repo: junthong/junthong.github.io
  branch: prepublish
  site_domain: statuesque-granita-8c2c00.netlify.com
publish_mode: editorial_workflow
media_folder: 'uploads'
collections:
  - name: 'articles' # Used in routes, e.g., /admin/collections/blog
    label: 'articles' # Used in the UI
    folder: '_articles' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}'
    fields: # The fields for each document, usually in front matter
      #- {label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog'}
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - { label: 'Author', name: 'author', required: false, widget: 'string' }
      - label: 'Author link'
        name: 'authorLink'
        required: false
        pattern: [ '/^https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$/','It must be a valid URL' ]
        widget: 'string'
      - label: 'Tags'
        name: 'tags'
        required: false
        widget: list
        field: { label: 'Tags', name: 'tag', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }